export const LOAD_CARS = '[CAR-LIST] LOAD CARS';
export const LOAD_CARS_SUCCESSFULLY = '[CAR-LIST] LOAD CARS SUCCESSFULLY';
export const LOAD_CARS_FAILED = '[CAR-LIST] LOAD CARS FAILED';
export const LOAD_CAR = '[CAR-LIST] LOAD CAR';
export const LOAD_CAR_SUCCESSFULLY = '[CAR-LIST] LOAD CAR SUCCESSFULLY';
export const LOAD_CAR_FAILED = '[CAR-LIST] LOAD CAR FAILED';
