export const LOAD_CARS = '[CAR-LIST] LOAD CARS';
export const LOAD_CARS_SUCCESSFULLY = '[CAR-LIST] LOAD CARS SUCCESSFULLY';
export const LOAD_FAILED = '[CAR-LIST] LOAD FAILED';
export const LOAD_CAR = '[CAR-LIST] LOAD CAR';
export const LOAD_CAR_SUCCESSFULLY = '[CAR-LIST] LOAD CAR SUCCESSFULLY';
